name: raffle_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  video_player: ^2.8.6
  url_launcher: ^6.3.0
  dio: ^5.4.3+1
  firebase_storage: ^12.0.0
  shimmer: ^3.0.0
  cloud_firestore: ^5.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  get_it: ^7.7.0
  go_router: ^14.1.4
  multiple_result: ^5.1.0
  equatable: ^2.0.5
  another_flushbar: ^1.12.30
  percent_indicator: ^4.2.3
  flutter_markdown: ^0.6.15
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  chewie: ^1.7.1
  dismissible_page: ^1.0.2
  story: ^1.1.0
  mobile_scanner: ^5.1.1
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.7.0
  qr_code_scanner: ^1.0.1
  flutter_card_swiper: ^7.0.1
  custom_refresh_indicator: ^3.1.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  remove_alpha_ios: true
flutter_native_splash:
  color: "#435784"
  image: assets/images/im_splash.png
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/gif/
    - assets/videos/
    - assets/md/





  fonts:
    - family: Noveo Sans
      fonts:
        - asset: assets/fonts/NoveoSans-Bold.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica/HelveticaNeueBold.ttf
        - asset: assets/fonts/helvetica/HelveticaNeueMedium.otf
        - asset: assets/fonts/helvetica/HelveticaNeueMedium400.otf
        - asset: assets/fonts/helvetica/Helvetica.ttf
        - asset: assets/fonts/helvetica/HelveticaNeueRoman.otf
        - asset: assets/fonts/helvetica/HelveticaNeueLight.ttf
        - asset: assets/fonts/helvetica/HelveticaNeueThin.otf
        - asset: assets/fonts/helvetica/HelveticaNeueUltraLight.otf

